---
- name: add debian mirror sources
  template: src=deb-sources.list
            dest=/etc/apt/sources.list
            owner=root
            group=root
            mode=0644
  notify: apt cache update

- name: install python-apt
  raw: /usr/bin/apt-get -y install python-apt
  notify: apt cache update

- name: update system
  apt: upgrade=dist

- name: dpkg add i386
  raw: /usr/bin/dpkg --add-architecture i386

- name: install required packages
  apt: state=latest name=$item update_cache=yes
  notify: purge nano
  with_items:
  - screen
  - curl
  - lib32gcc1

