---
- name: add debian mirror sources
  template: src=deb-sources.list
            dest=/etc/apt/sources.list
            owner=root
            group=root
            mode=0644
  notify: apt cache update

- name: install python-apt
  raw: /usr/bin/apt-get -y install python-apt
  notify: apt cache update

- name: update system
  apt: upgrade=dist

- name: dpkg add i386
  raw: /usr/bin/dpkg --add-architecture i386

- name: install required packages
  apt: state=latest name=$item update_cache=yes
  notify: purge nano
  with_items:
  - screen
  - curl
  - lib32gcc1

- name: create steam user
  user: createhome=yes
        home=/srv/steam
        name=steam
        state=present

- name: create /srv/steam/.ssh dir
  shell: /bin/mkdir /srv/steam/.ssh/ && /bin/chown -R steam /srv/steam/.ssh/
  notify: install steam authorized_keys

- name: grab steamcmd
  shell: /bin/mkdir /srv/steam/bin && /usr/bin/curl http://media.steampowered.com/installer/steamcmd_linux.tar.gz | /bin/tar xz -C /srv/steam/bin/

- name: steamcmd install l4d2 server
  shell: /srv/steam/bin/steamcmd +login anonymous +force_install_dir /srv/steam/l4d2 +app_update 222860 validate +quit

- name: copy over server configuration
  template: src=l4d2.cfg
            dest=/srv/steam/l4d2/left4dead2/left4dead2/server.cfg
            owner=steam
            group=steam
            mode=0644

