---
- name: steamcmd install csgo server
  shell: /srv/steam/bin/steamcmd.sh +login anonymous +force_install_dir /srv/steam/csgo +app_update 740 validate +quit

- name: generate passwords
  set_fact: 
            RCON_PASSWORD={{ lookup('password', 'creds/' + inventory_hostname + '.rcon length=5') }}
            SV_PASSWORD={{ lookup('password', 'creds/' + inventory_hostname + '.pw length=5') }}

- name: create /srv/steam/.steam/sdk32
  file: path=/srv/steam/.steam/sdk32
        owner=steam
        state=directory

- name: copy steamclient.so
  command: /bin/cp /srv/steam/bin/linux32/steamclient.so /srv/steam/.steam/sdk32/steamclient.so
           creates=/srv/steam/.steam/sdk32/steamclient.so

- name: fix csgo appid
  file: src=steam_appid.txt
        owner=steam
        mode=0600
        path=/srv/steam/csgo/steam_appid.txt
        state=file

- name: copy over server.cfg
  template: src=server.cfg
            dest=/srv/steam/csgo/csgo/cfg/server.cfg
            owner=steam
            group=steam
            mode=0644

- name: copy over cevo.cfg
  template: src=cevo.cfg
            dest=/srv/steam/csgo/csgo/cfg/cevo.cfg
            owner=steam
            group=steam
            mode=0644

- name: copy over cevo-ot.cfg
  template: src=cevo-ot.cfg
            dest=/srv/steam/csgo/csgo/cfg/cevo-ot.cfg
            owner=steam
            group=steam
            mode=0644

